// student-app/src/pages/Signup.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import axios from 'axios';

export default function Signup() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSignup = async (e) => {
    e.preventDefault();
    try {
      const { data } = await axios.post('http://localhost:5000/api/register', { 
        username, 
        password,
        role: 'student'
      });
      localStorage.setItem('token', data.token);
      localStorage.setItem('role', data.role);
      localStorage.setItem('username', data.username);
      
      navigate('/questions');
    } catch (err) {
      setError(err.response?.data?.error || 'Signup failed');
    }
  };

  return (
    <div className="auth-container">
      <form className="card" onSubmit={handleSignup} style={{ width: '350px' }}>
        <h2 style={{ marginBottom: '1.5rem', textAlign: 'center' }}>Student Sign Up</h2>
        {error && <p style={{ color: '#ef4444', marginBottom: '1rem', fontSize: '0.9rem', textAlign: 'center' }}>{error}</p>}
        <input 
          type="text" 
          placeholder="Choose Username" 
          className="input-field"
          value={username} onChange={e => setUsername(e.target.value)} 
          required 
        />
        <div style={{ position: 'relative', marginBottom: '1rem' }}>
          <input 
            type={showPassword ? 'text' : 'password'} 
            placeholder="Create Password" 
            className="input-field"
            style={{ marginBottom: 0 }}
            value={password} onChange={e => setPassword(e.target.value)} 
            required 
          />
          <button type="button" onClick={() => setShowPassword(!showPassword)} style={{ position: 'absolute', right: '10px', top: '10px', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}>
            {showPassword ? 'Hide' : 'Show'}
          </button>
        </div>
        <button type="submit" className="btn" style={{ width: '100%', marginBottom: '1rem' }}>Create Account</button>
        <p style={{ textAlign: 'center', fontSize: '0.9rem' }}>
          Already have an account? <Link to="/login" style={{ fontWeight: '600', textDecoration: 'none' }}>Log In</Link>
        </p>
      </form>
    </div>
  );
}

// admin-app/src/app/components/signup/signup.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div style="display: flex; justify-content: center; align-items: center; height: 80vh;">
      <div class="card" style="width: 350px;">
        <h2 style="text-align: center; margin-bottom: 1.5rem">Admin Sign Up</h2>
        <p *ngIf="error" style="color: #ef4444; margin-bottom: 1rem; text-align: center;">{{ error }}</p>
        <form (ngSubmit)="onSubmit()">
          <input class="input-field" type="text" [(ngModel)]="username" name="username" placeholder="Choose Username" required>
          <input class="input-field" type="password" [(ngModel)]="password" name="password" placeholder="Create Password" required>
          <button class="btn" type="submit" style="width: 100%; margin-bottom: 1rem;">Create Admin Account</button>
          <p style="text-align: center; font-size: 0.9rem; margin-top: 1rem; color: var(--text-muted);">
            Already have an account? <a routerLink="/login" style="font-weight: 600; text-decoration: none;">Log In</a>
          </p>
        </form>
      </div>
    </div>
  `
})
export class SignupComponent {
  username = '';
  password = '';
  error = '';
  api = inject(ApiService);
  router = inject(Router);

  onSubmit() {
    this.api.register({ username: this.username, password: this.password, role: 'admin' }).subscribe({
      next: (res: any) => {
        localStorage.setItem('token', res.token);
        localStorage.setItem('role', res.role);
        this.router.navigate(['/questions']);
      },
      error: (err) => {
        this.error = err.error?.error || 'Signup failed';
      }
    });
  }
}
